In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split


# Load dataset
df = pd.read_csv("Dataset1.csv")


# Prepare modeling dataset

model_data = df.groupby("Train_No").agg(
    Total_Distance=("Distance", "max"),
    Number_of_Stops=("Station_Name", "count")
).reset_index()


# Features

X = model_data[
    [
        "Total_Distance",
        "Number_of_Stops"
    ]
]


# Target variable
y = model_data["Total_Distance"]   # temporary target for splitting


# Split data

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [4]:
print("Training Dataset (80% data used for model learning)")
display(X_train)


print("Testing Dataset (20% data used for model evaluation)")
display(X_test)


summary = pd.DataFrame({
    "Dataset": [
        "Training Dataset",
        "Testing Dataset"
    ],
    "Total_Records": [
        X_train.shape[0],
        X_test.shape[0]
    ],
    "Number_of_Features": [
        X_train.shape[1],
        X_test.shape[1]
    ]
})


display(summary)

Training Dataset (80% data used for model learning)

       Total_Distance  Number_of_Stops
7173              160               14
3997               94               29
10594              28                2
6597                6                2
5920              154               12
...               ...              ...
5734              316               36
5191               34               15
5390               36               10
860               906               29
7270               93               12

[8890 rows x 2 columns]

Testing Dataset (20% data used for model evaluation)

       Total_Distance  Number_of_Stops
1864              491               25
3351              127               24
4680               29               18
5846               78                6
4419               71               24
...               ...              ...
11102              63               17
7988               83               12
4193               57               21
10804              10                2
9777                6                4

[2223 rows x 2 columns]

            Dataset  Total_Records  Number_of_Features
0  Training Dataset           8890                   2
1   Testing Dataset           2223                   2